<Type Name="TeamsAIAuthExceptionReason" FullName="Microsoft.Teams.AI.Exceptions.TeamsAIAuthExceptionReason">
  <TypeSignature Language="C#" Value="public enum TeamsAIAuthExceptionReason" />
  <TypeSignature Language="ILAsm" Value=".class public auto ansi sealed TeamsAIAuthExceptionReason extends System.Enum" />
  <TypeSignature Language="DocId" Value="T:Microsoft.Teams.AI.Exceptions.TeamsAIAuthExceptionReason" />
  <TypeSignature Language="VB.NET" Value="Public Enum TeamsAIAuthExceptionReason" />
  <TypeSignature Language="F#" Value="type TeamsAIAuthExceptionReason = " />
  <AssemblyInfo>
    <AssemblyName>Microsoft.Teams.AI</AssemblyName>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
  </AssemblyInfo>
  <Base>
    <BaseTypeName>System.Enum</BaseTypeName>
  </Base>
  <Docs>
    <summary>
            Cause of an authentication exception.
            </summary>
    <remarks>To be added.</remarks>
  </Docs>
  <Members>
    <Member MemberName="CompletionWithoutToken">
      <MemberSignature Language="C#" Value="CompletionWithoutToken" />
      <MemberSignature Language="ILAsm" Value=".field public static literal valuetype Microsoft.Teams.AI.Exceptions.TeamsAIAuthExceptionReason CompletionWithoutToken = int32(0)" />
      <MemberSignature Language="DocId" Value="F:Microsoft.Teams.AI.Exceptions.TeamsAIAuthExceptionReason.CompletionWithoutToken" />
      <MemberSignature Language="VB.NET" Value="CompletionWithoutToken" />
      <MemberSignature Language="F#" Value="CompletionWithoutToken = 0" Usage="Microsoft.Teams.AI.Exceptions.TeamsAIAuthExceptionReason.CompletionWithoutToken" />
      <MemberType>Field</MemberType>
      <AssemblyInfo>
        <AssemblyName>Microsoft.Teams.AI</AssemblyName>
        <AssemblyVersion>1.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>Microsoft.Teams.AI.Exceptions.TeamsAIAuthExceptionReason</ReturnType>
      </ReturnValue>
      <MemberValue>0</MemberValue>
      <Docs>
        <summary>
            The authentication flow completed without a token.
            </summary>
      </Docs>
    </Member>
    <Member MemberName="Other">
      <MemberSignature Language="C#" Value="Other" />
      <MemberSignature Language="ILAsm" Value=".field public static literal valuetype Microsoft.Teams.AI.Exceptions.TeamsAIAuthExceptionReason Other = int32(1)" />
      <MemberSignature Language="DocId" Value="F:Microsoft.Teams.AI.Exceptions.TeamsAIAuthExceptionReason.Other" />
      <MemberSignature Language="VB.NET" Value="Other" />
      <MemberSignature Language="F#" Value="Other = 1" Usage="Microsoft.Teams.AI.Exceptions.TeamsAIAuthExceptionReason.Other" />
      <MemberType>Field</MemberType>
      <AssemblyInfo>
        <AssemblyName>Microsoft.Teams.AI</AssemblyName>
        <AssemblyVersion>1.0.0.0</AssemblyVersion>
      </AssemblyInfo>
      <ReturnValue>
        <ReturnType>Microsoft.Teams.AI.Exceptions.TeamsAIAuthExceptionReason</ReturnType>
      </ReturnValue>
      <MemberValue>1</MemberValue>
      <Docs>
        <summary>
            Other error.
            </summary>
      </Docs>
    </Member>
  </Members>
</Type>
